version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: itemstock
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d itemstock"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - stockmanager_network  # ← adicionado

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: stockmanager_frontend
    ports:
      - "80:80"
    depends_on:
      - back-end
    networks:
      - stockmanager_network

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: stockmanager_backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/itemstock  # ← localhost → postgres
    ports:
      - "8080:8080"
    networks:
      - stockmanager_network

networks:
  stockmanager_network:
    driver: bridge